org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

mod_version = 1.0.2
maven_group = me.kall
archives_name = lastwords
enabled_platforms = fabric

minecraft_version = 1.21.8

fabric_loader_version = 0.18.0
fabric_api_version = 0.136.0+1.21.8

# Proxy
systemProp.http.proxyHost=localhost
systemProp.http.proxyPort=7897
systemProp.https.proxyHost=localhost
systemProp.https.proxyPort=7897